; TODO INSERT CONFIG CODE HERE USING CONFIG BITS GENERATOR
#include "p16f690.inc"

; CONFIG
; __config 0x30D4
 __CONFIG _FOSC_INTRCIO & _WDTE_OFF & _PWRTE_OFF & _MCLRE_OFF & _CP_OFF & _CPD_OFF & _BOREN_OFF & _IESO_OFF & _FCMEN_OFF

;CONSTS
POLYLOW EQU 0X21
POLYHIGH EQU 0X10   ;CRC16 POLYNOMIAL VALUE
 
INITLOW EQU 0XFF
INITHIGH EQU 0XFF   ;CRCSUM INIT VALUE
 
 
;VARS
CRCDAT EQU 0X20 ;8 BYTES    PUT THE DATA HERE
CRCSUM EQU 0X28 ;2 BYTES    GET THE CRC-16 SUM HERE

BITLOOPVAR EQU 0X2A
 
ORG 0X0000
;RES_VECT  CODE    0x0000            ; processor reset vector
    GOTO    START                   ; go to beginning of program

; TODO ADD INTERRUPTS HERE IF USED

;MAIN_PROG CODE                      ; let linker place main program

START
    
    ;+--------------+
    ;| CRC SUM DEMO |
    ;+--------------+
    
    ;PUT THE DATA INTO CRCDAT
    MOVLW 0X68
    MOVWF CRCDAT
    
    MOVLW 0X65
    MOVWF CRCDAT+1
    
    MOVLW 0X6C
    MOVWF CRCDAT+2
    
    MOVLW 0X6C
    MOVWF CRCDAT+3
    
    MOVLW 0X6F
    MOVWF CRCDAT+4
    
    MOVLW 0X50
    MOVWF CRCDAT+5
    
    MOVLW 0X49
    MOVWF CRCDAT+6
    
    MOVLW 0X43
    MOVWF CRCDAT+7
    
    CALL CRC16
    
    ;GET THE CHECKSUM IN CRCSUM
 
LOOP:

    GOTO LOOP                          ; loop forever

CRC16:
    MOVLW INITLOW
    MOVWF CRCSUM
    MOVLW INITHIGH
    MOVWF CRCSUM+1
    

    MOVF CRCDAT,W
    XORWF CRCSUM+1,F
    CALL PROCESSBITS
    
    MOVF CRCDAT+1,W
    XORWF CRCSUM+1,F
    CALL PROCESSBITS
    
    MOVF CRCDAT+2,W
    XORWF CRCSUM+1,F
    CALL PROCESSBITS
    
    MOVF CRCDAT+3,W
    XORWF CRCSUM+1,F
    CALL PROCESSBITS
    
    MOVF CRCDAT+4,W
    XORWF CRCSUM+1,F
    CALL PROCESSBITS
    
    MOVF CRCDAT+5,W
    XORWF CRCSUM+1,F
    CALL PROCESSBITS
    
    MOVF CRCDAT+6,W
    XORWF CRCSUM+1,F
    CALL PROCESSBITS
    
    MOVF CRCDAT+7,W
    XORWF CRCSUM+1,F
    CALL PROCESSBITS
    
    RETURN

PROCESSBITS:   
    MOVLW 0X08
    MOVWF BITLOOPVAR
BITLOOP:
    BTFSS CRCSUM+1,7
    GOTO MSBC
    
    BCF STATUS,C
    RLF CRCSUM,F
    RLF CRCSUM+1,F
    BCF STATUS,C
    
    MOVLW POLYLOW
    XORWF CRCSUM,F
    MOVLW POLYHIGH
    XORWF CRCSUM+1,F
    
    GOTO DONEMSBS
    
MSBC:
    BCF STATUS,C
    RLF CRCSUM,F
    RLF CRCSUM+1,F

DONEMSBS:
    DECFSZ BITLOOPVAR,F
    GOTO BITLOOP
    RETURN
    
    END
